- id: common-group
  name: COMMON GROUP
  language: script
  entry: ./run_hook_config common_grp
  verbose: true
  require_serial: true
- id: json-group
  name: JSON GROUP
  language: script
  entry: ./run_hook_config json_grp
  verbose: true
  require_serial: true
- id: yaml-group
  name: YAML GROUP
  language: script
  entry: ./run_hook_config yaml_grp
  verbose: true
  require_serial: true
- id: markdown-group
  name: MARKDOWN GROUP
  language: script
  entry: ./run_hook_config markdown_grp
  verbose: true
  require_serial: true
- id: python-group
  name: PYTHON GROUP
  language: script
  entry: ./run_hook_config python_grp
  verbose: true
  require_serial: true
- id: golang-group
  name: GOLANG GROUP
  language: script
  entry: ./run_hook_config golang_grp
  verbose: true
  require_serial: true
