- id: common-hkgrp
  name: COMMON GROUP
  language: script
  entry: ./run_hook_config common
  verbose: true
  require_serial: true
- id: python-hkgrp
  name: PYTHON GROUP
  language: script
  entry: ./run_hook_config python
  verbose: true
  require_serial: true
