#!/usr/bin/env python
import os
import sys

HERE = os.path.dirname(os.path.realpath(__file__))

CONFIG_MAPPING = {
    "common_grp": "config/common_hook.yaml",
    "json_grp": "config/json_hook.yaml",
    "yaml_grp": "config/yaml_hook.yaml",
    "markdown_grp": "config/markdown_hook.yaml",
    "python_grp": "config/python_hook.yaml",
}


def main(config_name: str):
    config_file = os.path.join(HERE, CONFIG_MAPPING[config_name])
    cmd = ["pre-commit", "run", "--config", config_file, "--files"] + sys.argv[2:]
    os.execvp(cmd[0], cmd)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
