repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks#check-added-large-files
      - id: check-added-large-files
        name: file - check size
        args:
          - --maxkb=1024
      # https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer
      - id: end-of-file-fixer
        name: file - fix newline
      # https://github.com/pre-commit/pre-commit-hooks#detect-private-key
      - id: detect-private-key
        name: content - detect private key
      # https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace
      - id: trailing-whitespace
        name: content - trimp space
        args:
          - --markdown-linebreak-ext=*
