repos:
- repo: https://github.com/jamesnguyen46/pre-commit-hook
  rev: v0.0.1
  hooks:
  - id: validate-python-file-name
    name: python - check file name
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    name: python - format code
- repo: https://github.com/pycqa/pylint
  rev: v2.13.9
  hooks:
  - id: pylint
    name: python - check lint
    args:
    - --fail-under=10
    - --max-line-length=120
    - --disable=C0114,C0115,C0116,R0903,W0703,R0201,E0401,E1101,R0801
