name: Pre-commit

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --verbose --all-files --show-diff-on-failure
  test:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit
      shell: bash
      run: |
        python -m pip install -U pip pre-commit
    - name: Test
      shell: bash
      run: |
        pre-commit try-repo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" --ref=$GITHUB_SHA --verbose --all-files --show-diff-on-failure
